title: <p align="center"> Rahul Kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahul-kumar-b38423154">LinkedIn</a> |
  <a href="https://github.com/RahulB268">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with HSBC, Capgemini & Virtusa at Data Analytics team.
  Working in Customer Subscription domain for last 4 years.
  <br>
  </p>

theme: jekyll-theme-minimal
